# Generated by Django 5.2.7 on 2025-12-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('auteur', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
