# Generated by Django 6.0 on 2025-12-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_slug_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa-folder', max_length=50),
        ),
    ]
