# Generated by Django 5.2.7 on 2026-01-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_likes_comment_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('subject', models.CharField(choices=[('general', 'Demande Générale'), ('submission', "Soumission d'Article"), ('partnership', 'Opportunité de Partenariat'), ('technical', 'Support Technique'), ('feedback', 'Commentaires & Suggestions'), ('other', 'Autre')], max_length=20, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Abonné à la newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
